return {
	AccountService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AchievementService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ActivityHistoryEventService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AdService = {
		detail = "A class that allows the display of mobile video ads." 
	},
	AnalyticsService = {
		detail = "Collection of methods that allows developers to track how users interact with their experiences." 
	},
	AnimationClipProvider = {
		detail = "Provides functions to load and preview `AnimationClip`." 
	},
	AnimationFromVideoCreatorService = {
		detail = "" 
	},
	AnimationFromVideoCreatorStudioService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AnnotationsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AppLifecycleObserverService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AppRatingPromptService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AppStorageService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AppUpdateService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AssetCounterService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AssetDeliveryProxy = {
		detail = "" 
	},
	AssetImportService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AssetManagerService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AssetService = {
		detail = "A non-replicated service that handles asset-related queries to the Roblox web API." 
	},
	AudioFocusService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AuroraScriptService = {
		detail = "",
		tags = {Enum.CompletionItemTag.Deprecated} 
	},
	AuroraService = {
		detail = "",
		tags = {Enum.CompletionItemTag.Deprecated, Enum.CompletionItemTag.RobloxPermissions} 
	},
	AvatarChatService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AvatarCreationService = {
		detail = "A service to support developer avatar creators." 
	},
	AvatarEditorService = {
		detail = "A service to support developer Avatar Editors." 
	},
	AvatarImportService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	AvatarSettings = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	BadgeService = {
		detail = "Provides information on badges and awards them." 
	},
	BrowserService = {
		detail = "" 
	},
	BugReporterService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	BulkImportService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CSGDictionaryService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CacheableContentProvider = {
		detail = "A variant of the `ContentProvider` that caches assets that have already been received. This service is not used directly, but it is used by the services that inherit from it." 
	},
	CalloutService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CaptureService = {
		detail = "A service which provides control over screenshot and video capture features." 
	},
	ChangeHistoryService = {
		detail = "Must be used by plugins to communicate to Studio how to undo and redo the changes which they make to the experience." 
	},
	ChangeHistoryStreamingService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	Chat = {
		detail = "Houses the Luau code responsible for running the legacy chat system." 
	},
	ChatbotUIService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CloudCRUDService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ClusterPacketCache = {
		detail = "An internal service meant to cache cluster packets." 
	},
	CollaboratorsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CollectionService = {
		detail = "A service which manages instance collections using assigned tags." 
	},
	CommerceService = {
		detail = "Supports real-world purchases that you can bundle with digital benefits." 
	},
	ConfigService = {
		detail = "" 
	},
	ConfigureServerService = {
		detail = "" 
	},
	ConnectivityService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ContentProvider = {
		detail = "Service that is used to load content, or assets, into a game." 
	},
	ContextActionService = {
		detail = "A service used to bind user input to contextual actions." 
	},
	ControllerService = {
		detail = "Container class for the `HumanoidController` among other classes." 
	},
	ConversationalAIAcceptanceService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CookiesService = {
		detail = "A backend service used by Roblox to control HTTP cookies. Its functions are not available to developers." 
	},
	CoreGui = {
		detail = "The CoreGui is a service used to store Guis created in-game by Roblox for the core user interface found in every game (such as the game menu, the playerlist, the backpack, etc.). It can also be used by `Plugin` in Roblox Studio.",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	CorePackages = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CoreScriptDebuggingManagerHelper = {
		detail = "" 
	},
	CoreScriptSyncService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CreationDBService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	CreatorStoreService = {
		detail = "" 
	},
	CrossDMScriptChangeListener = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	DataModelPatchService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	DataStoreService = {
		detail = "A game service that gives access to persistent data storage across places in a game." 
	},
	Debris = {
		detail = "Allows scheduling the guaranteed destruction of an object without yielding. ." 
	},
	DebugSettings = {
		detail = "Collection of various developer-facing diagnostics information." 
	},
	DebuggablePluginWatcher = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	DebuggerConnectionManager = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	DebuggerManager = {
		detail = "",
		tags = {Enum.CompletionItemTag.CommandLinePermissions} 
	},
	DebuggerUIService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	DeviceIdService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	DraftsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	DraggerService = {
		detail = "",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	EditableService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	EncodingService = {
		detail = "Service providing common encoding, hashing, and compression methods." 
	},
	EventIngestService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ExampleV2Service = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ExperienceAuthService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ExperienceNotificationService = {
		detail = "Service containing methods to validate users and prompt them to enable experience notifications." 
	},
	ExperienceService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ExperienceStateCaptureService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ExperienceStateRecordingService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ExplorerServiceVisibilityService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	FaceAnimatorService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	FacialAgeEstimationService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	FacialAnimationRecordingService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	FacialAnimationStreamingServiceV2 = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	FeatureRestrictionManager = {
		detail = "" 
	},
	FlagStandService = {
		detail = "An internal service responsible for handling the now deprecated `FlagStand` and `Flag` objects." 
	},
	FlyweightService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	FriendService = {
		detail = "An internal service which is used to send, cancel, accept and decline connection requests in-game." 
	},
	GamePassService = {
		detail = "A service associated with the legacy game pass system. Use `MarketplaceService` for all new work." 
	},
	GameSettings = {
		detail = "A container for miscellaneous in-game options." 
	},
	GamepadService = {
		detail = "The GamepadService is internally responsible for handling inputs from various controllers, such as Xbox One or PlayStation DualShock controllers." 
	},
	GenerationService = {
		detail = "Service that allows developers to generate 3D objects from text prompts." 
	},
	GenericChallengeService = {
		detail = "" 
	},
	Geometry = {
		detail = "An internal Roblox service which cannot be used by developers." 
	},
	GeometryService = {
		detail = "Service containing geometric operations." 
	},
	GroupService = {
		detail = "GroupService is a service that allows developers to fetch information about a Roblox group from within a game." 
	},
	GuiService = {
		detail = "Offers numerous properties and methods for working with `GuiObject`, player preferences, and other UI‑related tasks." 
	},
	GuidRegistryService = {
		detail = "An internal service, whose functionality is not accessible to developers." 
	},
	HSRDataContentProvider = {
		detail = "" 
	},
	HapticService = {
		detail = "Provides haptic feedback to controllers and devices." 
	},
	HarmonyService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	HeapProfilerService = {
		detail = "" 
	},
	HeatmapService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	HeightmapImporterService = {
		detail = "" 

	},
	Hopper = {
		detail = "Hopper is the original name of the StarterPack service." 
	},
	HttpRbxApiService = {
		detail = "An internal service whose functionality is not available to developers." 
	},
	HttpService = {
		detail = "Allows sending HTTP requests and provides various web-related and JSON methods." 
	},
	ILegacyStudioBridge = {
		detail = "" 
	},
	IXPService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	IncrementalPatchBuilder = {
		detail = "" 
	},
	InsertService = {
		detail = "Used to insert assets from the Roblox website." 
	},
	InstanceExtensionsService = {
		detail = "" 
	},
	InternalSyncService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	JointsService = {
		detail = "A service that stores joints created by surface connections." 
	},
	KeyboardService = {
		detail = "" 
	},
	KeyframeSequenceProvider = {
		detail = "Provides functions to load and preview `KeyframeSequence`." 
	},
	LSPFileSyncService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LanguageService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LegacyStudioBridge = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	Lighting = {
		detail = "The `Lighting` service controls global lighting in an experience. It includes a range of adjustable properties that you can use to change how lighting appears and interacts with other objects." 
	},
	LinkingService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LiveScriptingService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LiveSyncService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LocalStorageService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LocalizationService = {
		detail = "Handles automated translation." 
	},
	LodDataService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LogReporterService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	LogService = {
		detail = "A service that allows you to read outputted text." 
	},
	LoginService = {
		detail = "An internal service whose functionality is not available to developers." 
	},
	LuaSettings = {
		detail = "" 
	},
	LuaWebService = {
		detail = "An internal service, which is responsible for retrieving HTTP data from websites. Used by a range of services, including `MarketplaceService`, `InsertService` and `HttpService`. Its functions cannot be accessed by developers." 
	},
	LuauScriptAnalyzerService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	MLModelDeliveryService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	MLService = {
		detail = "" 
	},
	MarketplaceService = {
		detail = "The service responsible for in-experience transactions." 
	},
	MatchmakingService = {
		detail = "The service responsible for managing custom matchmaking data." 
	},
	MaterialGenerationService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	MaterialService = {
		detail = "The game service responsible for managing materials." 
	},
	MemStorageService = {
		detail = "" 
	},
	MemoryStoreService = {
		detail = "Exposes methods to access specific primitives within MemoryStore." 
	},
	MeshContentProvider = {
		detail = "An internal Roblox service that is responsible for fetching, parsing and caching meshes. This service cannot be used by developers." 
	},
	MessageBusService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	MessagingService = {
		detail = "Allows servers of the same experience to communicate with each other." 
	},
	MetaBreakpointManager = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	MicroProfilerService = {
		detail = "" 
	},
	ModerationService = {
		detail = "" 
	},
	MouseService = {
		detail = "" 
	},
	NetworkClient = {
		detail = "" 
	},
	NetworkServer = {
		detail = "" 
	},
	NetworkSettings = {
		detail = "Settings related to networked engine behaviors." 
	},
	NonReplicatedCSGDictionaryService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	NotificationService = {
		detail = "An internal service which cannot be used by developers." 
	},
	OmniRecommendationsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	OpenCloudService = {
		detail = "",
		tags = {Enum.CompletionItemTag.Deprecated} 
	},
	PackageService = {
		detail = "" 
	},
	PackageUIService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PartyEmulatorService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PatchBundlerFileWatch = {
		detail = "" 
	},
	PathfindingService = {
		detail = "Used to find logical paths between two points." 
	},
	PerformanceControlService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PermissionsService = {
		detail = "" 
	},
	PhysicsService = {
		detail = "" 
	},
	PhysicsSettings = {
		detail = "" 
	},
	PlaceAssetIdsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PlaceStatsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PlacesService = {
		detail = "" 
	},
	PlatformCloudStorageService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PlatformFriendsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PlayerDataService = {
		detail = "" 
	},
	PlayerEmulatorService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PlayerHydrationService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PlayerViewService = {
		detail = "Provides a way to get additional information about a player's view." 
	},
	Players = {
		detail = "A service that contains presently connected `Player` objects." 
	},
	PluginDebugService = {
		detail = "",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	PluginGuiService = {
		detail = "A service that stores `PluginGui` objects to be displayed in Roblox Studio.",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	PluginManagementService = {
		detail = "" 
	},
	PluginPolicyService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	PointsService = {
		detail = "This service controls the points award system used to showcase a player's achievements and participation throughout Roblox." 
	},
	PolicyService = {
		detail = "Helps you query information regarding policy compliance for players around the world based on age range, location, and platform type." 
	},
	ProcessInstancePhysicsService = {
		detail = "" 
	},
	ProximityPromptService = {
		detail = "Allows developers to interact with `ProximityPrompt` objects in a global way." 
	},
	PublishService = {
		detail = "" 
	},
	RbxAnalyticsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RecommendationService = {
		detail = "A service that provides an interface for you to manage and display personalized content recommendations." 
	},
	ReflectionService = {
		detail = "" 
	},
	RemoteCommandService = {
		detail = "" 
	},
	RemoteCursorService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RemoteDebuggerServer = {
		detail = "" 
	},
	RenderSettings = {
		detail = "" 
	},
	ReplicatedFirst = {
		detail = "A container whose contents are replicated to all clients (but not back to the server) first before anything else." 
	},
	ReplicatedStorage = {
		detail = "A container service for objects that are replicated to all clients." 
	},
	RibbonNotificationService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RobloxPluginGuiService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RobloxReplicatedStorage = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RobloxServerStorage = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RomarkRbxAnalyticsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RomarkService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RtMessagingService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RunService = {
		detail = "Service responsible for all runtime activity and progression of time." 
	},
	RuntimeContentService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	RuntimeScriptService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	SafetyService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ScriptChangeService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ScriptCloneWatcher = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ScriptCloneWatcherHelper = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ScriptCommitService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ScriptContext = {
		detail = "" 
	},
	ScriptEditorService = {
		detail = "This service is used for interacting with `ScriptDocument` instances.",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	ScriptProfilerService = {
		detail = "" 
	},
	ScriptRegistrationService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ScriptService = {
		detail = "An unimplemented service that has zero functionality, in a similar manner to the `LocalWorkspace` service." 
	},
	Selection = {
		detail = "The Selection service controls the `Instance` that are selected in Roblox Studio." 
	},
	SelectionHighlightManager = {
		detail = "" 
	},
	SerializationService = {
		detail = "" 
	},
	ServerScriptService = {
		detail = "A container service for server-only `Script` objects." 
	},
	ServerStorage = {
		detail = "A container whose contents are only accessible on the server. Objects descending from ServerStorage will not replicate to the client and will not be accessible from `LocalScript`." 
	},
	ServiceVisibilityService = {
		detail = "" 
	},
	SessionCheckService = {
		detail = "" 
	},
	SessionService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	SharedTableRegistry = {
		detail = "Provides a global registry of named `Datatype.SharedTable` objects." 
	},
	SlimContentProvider = {
		detail = "" 
	},
	SlimService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	SmoothVoxelsUpgraderService = {
		detail = "" 
	},
	SnippetService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	SocialService = {
		detail = "Facilitates social functions that impact relationships made on the Roblox platform." 
	},
	SolidModelContentProvider = {
		detail = "An internal service which serves no functionality to developers." 
	},
	SoundService = {
		detail = "A service that determines various aspects of how `Sound` play in the experience." 
	},
	SoundShimService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	SpawnerService = {
		detail = "An internal service that is responsible for the behavior of `SpawnLocation`. Its functionality is not accessible to developers." 
	},
	StartPageService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StarterGui = {
		detail = "A container for `LayerCollector` objects to be copied into the `PlayerGui` of `Player`. Also provides a range of functions for interacting with the `CoreGui`." 
	},
	StarterPack = {
		detail = "A service-level container whose contents are copied into each player's `Backpack` when the player spawns. It is generally used to hold `Tools`, but is sometimes used to hold `LocalScript|LocalScripts` to ensure that each player gets a copy." 
	},
	StarterPlayer = {
		detail = "A service which allows the defaults of properties in the `Player` object to be set." 
	},
	StartupMessageService = {
		detail = "" 
	},
	Stats = {
		detail = "Performance metrics for a game." 
	},
	StopWatchReporter = {
		detail = "" 
	},
	StreamingService = {
		detail = "",
		tags = {Enum.CompletionItemTag.CommandLinePermissions} 
	},
	Studio = {
		detail = "" 
	},
	StudioAssetService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioCameraService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioData = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioDeviceEmulatorService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioPublishService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioScriptDebugEventListener = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioSdkService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioService = {
		detail = "Provides access to configuration of Roblox Studio and allows importing files from the user's file system.",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	StudioUserService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StudioWidgetsService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	StylingService = {
		detail = "" 
	},
	SystemThemeService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TaskScheduler = {
		detail = "Collection of settings for the _Task Scheduler_ feature." 
	},
	TeamCreateData = {
		detail = "",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	TeamCreatePublishService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TeamCreateService = {
		detail = "",
		tags = {Enum.CompletionItemTag.PluginPermissions} 
	},
	Teams = {
		detail = "The Teams service holds a game's `Team` objects. `Team` objects must be parented to the Teams service." 
	},
	TelemetryService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TeleportService = {
		detail = "Enables transporting `Players` between places and servers." 
	},
	TemporaryCageMeshProvider = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TemporaryScriptService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TestService = {
		detail = "A service used by Roblox to run controlled tests of the engine. It is available for developers to use, to a limited degree." 
	},
	TextBoxService = {
		detail = "" 
	},
	TextChatService = {
		detail = "A service handling in-experience text chat." 
	},
	TextService = {
		detail = "The TextService is a service internally responsible for handling the display of text in the game." 
	},
	TextureGenerationService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	ThirdPartyUserService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TimerService = {
		detail = "An internal service responsible for scheduling timed events. It is used by the `Debris` class. Its functionality can not be accessed by developers." 
	},
	ToastNotificationService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TouchInputService = {
		detail = "An internal service responsible for touch inputs on mobile devices." 
	},
	TracerService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TutorialService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	TweenService = {
		detail = "Used to create `Tween` which interpolate, or tween, the properties of instances." 
	},
	UGCAvatarService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	UGCValidationService = {
		detail = "" 
	},
	UIDragDetectorService = {
		detail = "" 
	},
	UniqueIdLookupService = {
		detail = "" 
	},
	UnvalidatedAssetService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	UserGameSettings = {
		detail = "The UserGameSettings is a singleton class found inside of the `UserSettings` singleton. It holds various persistent settings relating to how the user wants to control their camera, and their character." 
	},
	UserInputService = {
		detail = "`UserInputService` is primarily used to detect the input types available on a user's device, as well as detect input events." 
	},
	UserService = {
		detail = "A service that handles queries regarding users on the Roblox platform." 
	},
	UserStorageService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	VRService = {
		detail = "Service responsible for handling interactions between Roblox and Virtual Reality (VR)." 
	},
	VRStatusService = {
		detail = "" 
	},
	VersionControlService = {
		detail = "",
		tags = {Enum.CompletionItemTag.CommandLinePermissions} 
	},
	VideoCaptureService = {
		detail = "" 
	},
	VideoScreenCaptureService = {
		detail = "" 
	},
	VideoService = {
		detail = "An internal service that offers no functionality to developers." 
	},
	VirtualInputManager = {
		detail = "An internal service that offers no functionality to developers." 
	},
	VirtualUser = {
		detail = "VirtualUser is a service that allows you to record the inputs of a user, and then play it back to a limited extent." 
	},
	VisibilityCheckDispatcher = {
		detail = "" 
	},
	Visit = {
		detail = "The Visit service is a backend service used by Roblox. Its functions are not accessible to developers in any form." 
	},
	VisualizationModeService = {
		detail = "" 
	},
	VoiceChatInternal = {
		detail = "" 
	},
	VoiceChatService = {
		detail = "VoiceChatService is responsible for voice chat's high-level functionality." 
	},
	WebSocketService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	WebViewService = {
		detail = "",
		tags = {Enum.CompletionItemTag.RobloxPermissions} 
	},
	Workspace = {
		detail = "Workspace houses 3D objects which are rendered to the 3D world. Objects not descending from it will not be rendered or physically interact with the world." 
	},
}
